apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  labels:
    app: my-app
data:
  # configuration that your app will use
  APP_MODE: "production"
  MAX_CONNECTIONS: "100"
  FEATURE_FLAG_X: "true"
  LOG_LEVEL: "info"
