apiVersion: v1
kind: ConfigMap
metadata:
  name: properties-config
  namespace: default
data:
  application.properties: |
    app.name=MyApplication
    app.version=1.0.0
    app.environment=production
