apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  namespace: default
  labels:
    app: my-app
    tier: frontend
spec:
  type: ClusterIP # default type (internal only)
  selector:
    app: my-app
  ports:
  - name: http
    protocol: TCP
    port: 80 # Service port
    targetPort: 80 # Pod container port
