apiVersion: v1
apiVersion_info:
  description: apiVersion field
  type: string
  required: true
kind: ConfigMap
kind_info:
  description: kind field
  type: string
  required: true
metadata:
  name: properties-config
  name_info:
    description: name field
    type: string
    required: false
  namespace: default
  namespace_info:
    description: namespace field
    type: string
    required: false
metadata_info:
  description: metadata field
  type: object
  required: true
data:
  application.properties: 'app.name=MyApplication

    app.version=1.0.0

    app.environment=production

    '
  application.properties_info:
    description: application.properties field
    type: string
    required: false
data_info:
  description: data field
  type: object
  required: false
